apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: city-events
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'event-service'
        static_configs:
          - targets: ['event-service:8082']

      - job_name: 'auth-service'
        static_configs:
          - targets: ['auth-service:8081']
          
      - job_name: 'feed-service'
        static_configs:
          - targets: ['feed-service:8084']

      - job_name: 'bff-service'
        static_configs:
          - targets: ['bff-service:8080']

      - job_name: 'join-service'
        static_configs:
          - targets: ['join-service:8083']
