# services/email-service/air.toml
root = "."
tmp_dir = "tmp"

[build]
  # 明确指向 main.go
  cmd = "go build -o ./tmp/main.exe ./api/cmd/main.go"
  # Windows 下直接运行生成的 exe
  bin = "tmp\\main.exe"
  
  include_dir = ["api", "internal"]
  include_ext = ["go", "env"]
  exclude_dir = ["tmp", "vendor", "testdata"]
  delay = 1000
  stop_on_error = true
  send_interrupt = true
  kill_delay = "2s"

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true