#:schema https://json.schemastore.org/any.json

root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ./api/cmd"

  # 关键：必须是 powershell.exe
  bin = "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
  args_bin = [
    "-NoProfile",
    "-ExecutionPolicy", "Bypass",
    "-Command",
    "Get-Content .env | ForEach-Object { if ($_ -match '^[\\s]*#' -or $_ -match '^[\\s]*$') { return }; $k,$v = $_ -split '=',2; [Environment]::SetEnvironmentVariable($k.Trim(), $v.Trim(), 'Process') }; & .\\tmp\\main.exe"
  ]


  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "tpl", "tmpl", "html"]

  send_interrupt = true
  kill_delay = "2s"

  log = "build-errors.log"

  stop_on_error = true


# ✅ ADD THIS
env_file = ".env"

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
